- name: Bootstrap environment
  hosts: localhost
  vars:
    dotfiles_git_repository: https://github.com/borislas/dotfiles.git
    desktop: gnome
  roles:
  - core
  - desktop
  - apps
  #  - configuration
