- name: Fedora | Enable the RPM Fusion repository
  become: yes
  dnf:
    name: 
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: yes
    enablerepo: fedora-cisco-openh264

- name: Fedora | Install packages (dnf)
  become: yes
  dnf:
    name:
    - "@hardware-support"
    - "@c-development"
    - "@container-management"
    - "@fonts"
    - flatpak
    - distrobox
    - kubernetes-client
    - distribution-gpg-keys
    - mozilla-openh264
    - libavcodec-freeworld
    - mesa-va-drivers-freeworld
    - zsh
    - git
    - foot
    - neovim
    - steam-devices
    - dbus-devel 
    - pkgconf-pkg-config
    - ufraw
    - pipx

- name: Fedora | AMD GPU packages
  become: yes
  dnf:
    name:
    - rocm-opencl 
    - rocm-clinfo
    - rocm-device-libs
    - rocminfo
  when: gpu_type == "amd"

- name: Fedora | Nvidia GPU packages
  become: yes
  dnf:
    name:
    - xorg-x11-drv-nvidia-cuda
    - akmod-nvidia
  when: gpu_type == "nvidia"

- name: Fedora | Enable raw photos preview with ufraw
  become: yes
  copy:
    content: |
      [Thumbnailer Entry]
      TryExec=ufraw
      Exec=ufraw-batch --embedded-image --out-type=png --size=%s %i --overwrite --silent --output=%o
      MimeType=application/x-ufraw;image/x-dcraw;image/x-3fr;image/x-adobe-dng;image/x-arw;image/x-bay;image/x-canon-cr2;image/x-canon-crw;image/x-cap;image/x-cr2;image/x-crw;image/x-dcr;image/x-dcraw;image/x-dcs;image/x-dng;image/x-drf;image/x-eip;image/x-erf;image/x-fff;image/x-fuji-raf;image/x-iiq;image/x-k25;image/x-kdc;image/x-mef;image/x-minolta-mrw;image/x-mos;image/x-mrw;image/x-nef;image/x-nikon-nef;image/x-nrw;image/x-olympus-orf;image/x-orf;image/x-panasonic-raw;image/x-pef;image/x-pentax-pef;image/x-ptx;image/x-pxn;image/x-r3d;image/x-raf;image/x-raw;image/x-rw2;image/x-rwl;image/x-rwz;image/x-sigma-x3f;image/x-sony-arw;image/x-sony-sr2;image/x-sony-srf;image/x-sr2;image/x-srf;image/x-x3f;image/x-panasonic-raw2;image/x-nikon-nrw; 
    dest: /usr/share/thumbnailers/ufraw.thumbnailer

