- name: Fedora | Enable the RPM Fusion repository
  become: yes
  dnf:
    name: 
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: yes
    enablerepo: fedora-cisco-openh264

- name: Fedora | Install packages (dnf)
  become: yes
  dnf:
    name:
    - flatpak
    - distribution-gpg-keys
    - mozilla-openh264
    - libavcodec-freeworld
    - mesa-va-drivers-freeworld
    - zsh
    - git
    - tmux
    - neovim
    - stow
    - make
    - steam-devices
