- name: Detect GPU type
  include_tasks: gpufact.yml

- name: Install Fedora base packages
  include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"
- name: Install Arch Linux base packages
  include_tasks: arch.yml
  when: ansible_distribution == "Arch Linux"
